POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1dXJpIiwiaWQiOiI1ZWYyMTc4MDVlZTNjNTVhOWZiNDEwMjEiLCJpYXQiOjE1OTI5MjQwNDN9.bhybvLbaMaJ7T2KNyEkFP7Rga8HkWIGF2diJUCYFtc0

{
  "title": "this blog shouldn't show",
  "author": "Mikko Mallikas",
  "url": "www.blog.com",
  "likes": 1000,
  "userId": "5ef0f61b4e17db6a00199409"
}